// data.js — נתוני הקורס (נושאים, קטגוריות). לעריכת תוכן — ערוך כאן.
// ═══════════════════════════════════════════════════════════
// DATA
// ═══════════════════════════════════════════════════════════
const TOPICS = [
  // ── חלק א ──
  {cat:"surgery_shock",catLabel:"כירורגיה ומצבי הלם",icon:"🏥",part:"א",id:"periop",name:"טיפול סביב ניתוחי",hours:22,pages:165,meta:"Pre-op · Intra-op · Post-op · סיבוכים · צנתר שתן",brunner:"פרקים 14-16",subs:["סוגי ניתוחים — סיווג לפי מטרה, היקף ודחיפות","Preoperative: הערכת סיכון ניתוחי לפי מערכות גוף","Preoperative: הסכמה מדעת (חוק זכויות החולה) + הכנת המטופל","Intraoperative: צוות חדר ניתוח — תפקידים וסביבה","Intraoperative: סוגי הרדמה, תרופות וסיבוכים, תנוחות","Postoperative: עקרונות טיפול לאחר ניתוח","Postoperative: סיבוכים מוקדמים ומאוחרים","שחרור מטופל, הכנה ושיקום","החדרת והוצאת צנתר שלפוחית השתן — חוזרים"]},
  {cat:"surgery_shock",catLabel:"כירורגיה ומצבי הלם",icon:"🏥",part:"א",id:"shock",name:"מצבי הלם",hours:8,pages:76,meta:"Hypovolemic · Cardiogenic · Septic · Anaphylactic · Obstructive",brunner:"פרק 11",subs:["Hypovolemic Shock — גורמים, שלבים, טיפול","Cardiogenic Shock — גורמים ועקרונות טיפול","Anaphylactic Shock — זיהוי, אפינפרין, מניעה","Septic Shock — SIRS, Sepsis, גורמים, טיפול","Neurogenic Shock + Obstructive Shock","שלבי ההלם: Compensated → Progressive → Irreversible","ניהול סיעודי — ניטור, גישה ורידית, תרופות"]},
  {cat:"respiratory",catLabel:"מערכת הנשימה",icon:"🫁",part:"א",id:"respiratory",name:"מערכת הנשימה",hours:42,pages:473,meta:"COPD · Asthma · Pneumonia · ARDS · PE · Mechanical Ventilation",brunner:"פרקים 17-20",subs:["אנטומיה, פיזיולוגיה ואומדן מערכת הנשימה","בדיקות: PFT, ABG, Pulse Oximetry, Bronchoscopy, Thoracentesis","הפרעות מאזן חומצי-בסיסי: Respiratory & Metabolic Acidosis/Alkalosis","Asthma + Status Asthmaticus","COPD: Chronic Bronchitis & Emphysema — שלבי GOLD","Pulmonary Fibrosis, Pulmonary Arterial Hypertension, Lung Cancer","Atelectasis, Pneumonia, Pulmonary TB, Lung Abscess","ARF, ARDS, Pulmonary Embolism","חבלות חזה: Flail Chest, Pneumothorax, Hemothorax, Cardiac Tamponade","טיפול בחמצן: Low Flow / High Flow Systems","NIV: CPAP, BiPAP","Invasive: Intubation, Tracheostomy, Mechanical Ventilation & Weaning"]},
  {cat:"cardio",catLabel:"לב וכלי דם",icon:"🫀",part:"א",id:"cardio",name:"מערכת הלב וכלי הדם",hours:40,pages:438,meta:"ECG · ACS · MI · HF · Arrhythmias · Endocarditis · HTN",brunner:"פרקים 21-25",subs:["אנטומיה, פיזיולוגיה ואומדן הלב","בדיקות: ECG, Echo, Cardiac Cath, Stress Test, Hemodynamic Monitoring","פענוח אק\"ג: קצב סינוס תקין, ציר, גל P-QRS-T","הפרעות קצב: Sinus, Atrial (Afib/Flutter), Junctional, Ventricular (VT/VF)","Heart Blocks: 1st, 2nd (Type I/II), 3rd Degree — טיפול וקוצבים","Defib + AED — חוזר מנהל האחיות","מחלות כליליות: Stable Angina, ACS, NSTEMI, STEMI","PCI & CABG — טיפול סיעודי","מחלות מסתמיות: Mitral Valve, Aortic Valve — Stenosis & Regurgitation","Heart Failure: Left/Right/Congestive, Pulmonary Edema","מחלות דלקתיות: Endocarditis, Pericarditis, Myocarditis, Rheumatic Carditis","יתר לחץ דם: אבחון, סיבוכים רב-מערכתיים, טיפול"]},
  {cat:"cardio",catLabel:"לב וכלי דם",icon:"🫀",part:"א",id:"vascular",name:"מחלות כלי דם פריפריים",hours:14,pages:175,meta:"PAD · DVT · Aneurysm · Lymphedema · Raynaud's",brunner:"פרקים 26-27",subs:["בדיקות: Doppler, Duplex US, CT, MRA, Angiography, Venography","הפרעות עורקיות: PAD, Aortic Aneurysm & Dissection","Arterial Embolism & Thrombosis, Raynaud's Phenomenon","הפרעות ורידיות: VTE/DVT, Chronic Venous Insufficiency, Leg Ulcer","Varicose Veins — טיפול ומניעה","הפרעות לימפתיות: Lymphedema, Cellulitis, Lymphangitis"]},
  {cat:"gastro",catLabel:"מערכת העיכול",icon:"🫃",part:"א",id:"gastro",name:"מערכת העיכול",hours:52,pages:628,meta:"GERD · Peptic Ulcer · Cirrhosis · IBD · Colorectal Cancer · Pancreatitis",brunner:"פרקים 38-44",subs:["אנטומיה, פיזיולוגיה ואומדן מערכת העיכול","בדיקות: אנדוסקופיה (Gastroscopy, Colonoscopy, ERCP), CT, MRI","מחלות ושט: Achalasia, GERD, Barrett Esophagus, Hiatal Hernia, Cancer","מחלות קיבה ותריסריון: Gastritis, Peptic Ulcer Disease, Gastric Cancer","Bariatric Surgery — טיפול סיעודי","מחלות כבד: Viral/Nonviral Hepatitis, Cirrhosis, Liver Cancer","מחלות מרה: Cholecystitis, Cholelithiasis","מחלות לבלב: Acute/Chronic Pancreatitis, Pancreatic Cancer","מחלות מעיים: IBS, Peritonitis, Appendicitis, Intestinal Obstruction","IBD: Crohn's Disease, Ulcerative Colitis — הבדלים, טיפול","Colorectal Cancer, Polyps + Ileostomy/Colostomy — עקרונות טיפול","Hemorrhoids, Anal Fissure, Anorectal Abscess"]},
  {cat:"endocrine",catLabel:"מערכת הורמונלית",icon:"⚗️",part:"א",id:"endocrine",name:"מערכת הורמונלית",hours:20,pages:211,meta:"DM Type 1&2 · Thyroid · Adrenal · Pituitary · SIADH",brunner:"פרקים 45-46",subs:["אנטומיה, פיזיולוגיה ואומדן המערכת ההורמונלית","היפופיזה: Hypopituitarism, Hyperpituitarism, Diabetes Insipidus, SIADH","בלוטת התריס: Hypothyroidism, Hyperthyroidism, Thyroiditis, Thyroid Cancer","בלוטת יותרת הכליה: Addison's Disease, Cushing's, Hyperaldosteronism","בלוטת יותרת התריס: Hypoparathyroidism, Hyperparathyroidism","Diabetes Mellitus Type 1 — פתופיזיולוגיה, אינסולין","Diabetes Mellitus Type 2 — גורמי סיכון, ניהול תרופתי","סיבוכי סוכרת: DKA, HHS, היפוגליקמיה, כף רגל סוכרתית"]},
  // ── חלק ב ──
  {cat:"nephrology",catLabel:"נפרולוגיה",icon:"💧",part:"ב",id:"nephrology",name:"נפרולוגיה",hours:20,pages:188,meta:"Glomerulonephritis · PKD · Renal Cancer · AKI · CKD/ESRD · Dialysis",brunner:"פרקים 47-48",subs:["אנטומיה, פיזיולוגיה ותפקידי הכליה","בדיקות אבחון: BUN, Creatinine, GFR, ניתוח שתן, ביופסיית כליה","Glomerulonephritis — חריף/כרוני + Nephrotic Syndrome","מחלת כליה פוליציסטית (Polycystic Kidney Disease)","סרטן הכליה (Renal Cancer)","Acute Kidney Injury (AKI) — הגדרה, שלבים (Prerenal/Intrarenal/Postrenal), טיפול","אי ספיקת כליות כרונית וסופנית (CKD/ESRD) — שלבים, ניהול","Hemodialysis — גישה ורידית (AVF/צנתר), עקרונות, סיבוכים","Peritoneal Dialysis — עקרונות, סיבוכים (Peritonitis)","פתולוגיות נוספות במערכת הכליה"]},
  {cat:"urology",catLabel:"מערכת השתן",icon:"🫘",part:"ב",id:"urology",name:"מערכת השתן",hours:32,pages:279,meta:"CKD · AKI · Dialysis · UTI · BPH · Prostate Cancer",brunner:"פרקים 47-49",subs:["אנטומיה, פיזיולוגיה ואומדן מערכת השתן","בדיקות: BUN, Creatinine, GFR, ניתוח שתן, Cystoscopy, Renal Biopsy","נפרולוגיה: Chronic Kidney Disease (CKD) — שלבים","Acute Kidney Injury (AKI) — גורמים, שלבים, טיפול","Glomerulonephritis, Nephrotic Syndrome, Polycystic Kidney","Hemodialysis — גישה ורידית, עקרונות, סיבוכים","Peritoneal Dialysis — עקרונות וסיבוכים","UTI — עליון ותחתון, גורמים, טיפול, מניעה","Urinary Incontinence, Retention, Neurogenic Bladder","Urolithiasis (אבני כליה) + Bladder Cancer","BPH — אבחון, TURP, טיפול תרופתי","Prostate Cancer, Testicular Cancer, Orchitis"]},
  {cat:"immune_rheum",catLabel:"מערכת חיסונית וראומטולוגיה",icon:"🛡️",part:"ב",id:"immune",name:"מערכת חיסונית",hours:12,pages:291,meta:"HIV · Anaphylaxis · RA · SLE · Gout",brunner:"פרקים 31-34",subs:["כשל חיסוני ראשוני + HIV/AIDS — סיווג, מעקב, ART","Anaphylaxis — פתופיזיולוגיה, טיפול מיידי, מניעה (חוזר 204/2023)","Urticaria, Angioedema, Food Allergy, Latex Allergy","Rheumatoid Arthritis — אבחון (RF, Anti-CCP), טיפול DMARD","Osteoarthritis — הבדל מ-RA, טיפול, החלפת מפרק","SLE — קריטריוני SLICC, איברי מטרה, טיפול","Scleroderma, Sjögren's, Polymyositis, Polymyalgia Rheumatica","Gout + Fibromyalgia"]},
  {cat:"skin_burns",catLabel:"עור וכוויות",icon:"🔥",part:"ב",id:"skin",name:"מחלות עור",hours:8,pages:187,meta:"Dermatitis · Psoriasis · Herpes · Melanoma · SCC",brunner:"פרקים 55-56",subs:["בדיקות אבחון: Skin Biopsy, Wood Lamp","מחלות אלרגיות/דלקתיות: Pruritus, Dermatitis (Seborrheic, Contact, Atopic)","Psoriasis, Stevens-Johnson Syndrome, Toxic Epidermal Necrolysis","זיהומים ויראליים: Herpes Simplex, Herpes Zoster","זיהומים חיידקיים: Folliculitis, Furuncles, Cellulitis","זיהומים פטרייתיים: Tinea, Candidiasis","זיהומים טפיליים: Scabies, Pediculosis","גידולים ממאירים: Melanoma, SCC, BCC, Kaposi Sarcoma"]},
  {cat:"skin_burns",catLabel:"עור וכוויות",icon:"🔥",part:"ב",id:"burns",name:"כוויות",hours:4,pages:88,meta:"שלבים · Parkland Formula · Phases · שיקום",brunner:"פרק 57",subs:["פתופיזיולוגיה ושינויים רב-מערכתיים בפגיעת כוויות","סוגי כוויות ושיטות סיווג חומרה (TBSA, Rule of Nines, Lund-Browder)","Emergent/Resuscitation Phase — נוזלים, Parkland Formula","Acute/Healing Phase — טיפול בפצע, הדבקה","Rehabilitative Phase — שיקום, מניעת כיווץ, פסיכולוגיה"]},
  {cat:"senses",catLabel:"עיניים ואף-אוזן-גרון",icon:"👁️",part:"ב",id:"eyes",name:"מחלות עיניים",hours:8,pages:107,meta:"Cataract · Glaucoma · Macular Degeneration · Retinal Detachment",brunner:"פרק 58",subs:["אנטומיה, פיזיולוגיה ואומדן הראייה","בדיקות: Tonometry, Ophthalmoscopy, Fluorescein Angiography, OCT","Cataract — אבחון, פיאקואמולסיפיקציה, טיפול סיעודי","Glaucoma — open-angle vs angle-closure, טיפול תרופתי וכירורגי","הפרעות ברשתית: Age-Related Macular Degeneration, Retinal Detachment","Conjunctivitis — זיהומי ואלרגי, מניעת הדבקה","שגיאות שבירה: Myopia, Hyperopia, Astigmatism","חבלות ומצבי חירום: Foreign Body, Penetrating Injury"]},
  {cat:"senses",catLabel:"עיניים ואף-אוזן-גרון",icon:"👂",part:"ב",id:"ent",name:"מחלות אף-אוזן-גרון",hours:10,pages:72,meta:"Otitis Media · Hearing Loss · Rhinitis · Sinusitis · Laryngeal Cancer",brunner:"פרק 59",subs:["אנטומיה, פיזיולוגיה ואומדן אף-אוזן-גרון","בדיקות: Audiometry, Tympanogram, CT, MRI","מחלות אף: Allergic/Viral Rhinitis, Sinusitis, Epistaxis, Nasal Fracture","אובדן שמיעה — סוגים, אבחון, שיקום (מכשיר שמיעה, שתל קוכלארי)","הפרעות אוזן חיצונית/תיכונה: Otitis Externa/Media, Tympanic Membrane Perf.","הפרעות אוזן פנימית: Meniere's Disease, BPPV, Tinnitus","צוואר וגרון: Pharyngitis, Tonsillitis, Obstructive Sleep Apnea","Laryngitis, Laryngeal Obstruction, Cancer of the Larynx"]},
  {cat:"neuro",catLabel:"מערכת העצבים",icon:"🧠",part:"ב",id:"neuro",name:"מערכת העצבים (נוירולוגיה)",hours:32,pages:440,meta:"Stroke · Epilepsy · MS · Parkinson's · Meningitis · GBS",brunner:"פרקים 60-65",subs:["אנטומיה, פיזיולוגיה ואומדן נוירולוגי (כולל GCS)","בדיקות: CT, MRI, EEG, EMG, Lumbar Puncture, Cerebral Angiography","Altered Level of Consciousness — גורמים, ניהול","Seizures & Epilepsy — סיווג, Status Epilepticus, טיפול","Migraine Headache","TIA + Ischemic Stroke — FAST, tPA, חלון טיפול","Hemorrhagic Stroke — SAH, ICH (חוזרים 190-193)","מחלות זיהומיות: Meningitis, Encephalitis, Brain Abscess","מחלות אוטואימוניות: Multiple Sclerosis (MS), Myasthenia Gravis, GBS","מחלות ניווניות: Parkinson's Disease, ALS, Huntington Disease","גידולי מוח וחוט שדרה — Primary & Secondary","מוות מוחי — הגדרה, קריטריונים, תהליך"]},
  {cat:"musculoskeletal",catLabel:"שלד ושרירים",icon:"🦴",part:"ב",id:"musculoskeletal",name:"מערכת השלד והשרירים",hours:20,pages:316,meta:"Osteoporosis · Fractures · Osteomyelitis · Amputation · Low Back Pain",brunner:"פרקים 35-37",subs:["אנטומיה, פיזיולוגיה ואומדן שלד-שרירים","בדיקות: Bone Density (DXA), CT, MRI, Bone Scan, Arthroscopy","Osteoporosis + Osteomalacia — גורמי סיכון, מניעה, טיפול","Osteoarthritis — Total Hip/Knee Replacement, טיפול סיעודי","Osteomyelitis + Septic Arthritis + Bone Tumors","טראומטולוגיה: שברים — סיווג, שלבי ריפוי, סיבוכים מוקדמים/מאוחרים","Compartment Syndrome, Fat Embolism, DVT — מניעה","פריקות, פציעות גידים וסחוסים","Amputation — Elective & Traumatic, שיקום","Low Back Pain, Herniated Cervical/Lumbar Disk"]},
  {cat:"onco_hematology",catLabel:"אונקולוגיה, המטולוגיה ושד",icon:"🎗️",part:"ב",id:"oncology",name:"מחלה ממארת (אונקולוגיה)",hours:14,pages:241,meta:"Staging · Chemo · Immunotherapy · Palliative Care · מצבי חירום",brunner:"פרקים 12-13",subs:["פתופיזיולוגיה: Grading, Ploidy, Staging (TNM), גורמי סיכון","טיפול כירורגי — Debulking, Prophylactic Surgery","טיפול קרינתי — סוגים, תופעות לוואי","כימותרפיה — מנגנוני פעולה, תופעות לוואי, ניהול סיעודי","Targeted Therapy & Immunotherapy","Hematopoietic Stem Cell Transplantation","מצבי חירום: Sepsis, DIC, SIADH, Spinal Cord Compression","Hypercalcemia, Superior Vena Cava Syndrome, Tumor Lysis Syndrome","טיפול פליאטיבי: עקרונות, ניהול כאב (WHO Ladder), תסמינים","Palliative Care: תמיכה פסיכו-סוציאלית, חוק החולה הנוטה למות"]},
  {cat:"onco_hematology",catLabel:"אונקולוגיה, המטולוגיה ושד",icon:"🩸",part:"ב",id:"hematology",name:"מערכת הדם והלימפה",hours:14,pages:265,meta:"Anemia · Leukemia · Lymphoma · DIC · Hemophilia",brunner:"פרקים 28-30",subs:["אנטומיה, פיזיולוגיה ואומדן מערכת הדם","בדיקות: CBC, Reticulocytes, Coagulation (PT/INR/PTT), Bone Marrow","אנמיות: Iron Deficiency, Anemia of Chronic Disease, Aplastic Anemia","אנמיות: Megaloblastic (B12/Folate), Sickle Cell Disease, Thalassemia","Polycythemia Vera + Neutropenia","ממאירויות: AML, CML, CLL — Leukemia","Hodgkin Lymphoma, Non-Hodgkin Lymphoma, Multiple Myeloma","הפרעות קרישה: Thrombocytopenia (ITP), Hemophilia, Von Willebrand","DIC — פתופיזיולוגיה, ניטור, טיפול","Stem Cell Transplantation & Therapeutic Apheresis"]},
  {cat:"onco_hematology",catLabel:"אונקולוגיה, המטולוגיה ושד",icon:"🎀",part:"ב",id:"breast",name:"הפרעות בשד",hours:6,pages:76,meta:"Breast Cancer · Mastectomy · BRCA · Fibrocystic · שחזור",brunner:"פרק 52",subs:["בדיקת שד עצמית + Mammography, US, MRI, Biopsy, BRCA1/BRCA2","סרטן השד — סוגים, שלבי TNM, גורמי סיכון","טיפול כירורגי: Lumpectomy, Mastectomy, Sentinel Node Biopsy","טיפולים משלימים: קרינה, כימותרפיה, Hormonal, Targeted (Herceptin)","שחזור שד — סוגים ומועד ביצוע","מצבים שפירים: Fibrocystic Changes, Fibroadenoma, LCIS"]},
];


// תאריכי מבחנים (ברירת מחדל למעקב הלו"ז — ניתן לשינוי בפאנל ההגדרות)
const EXAM_DATES = { "א": "2026-08-02", "ב": "2026-09-06" };

const CAT_ORDER = ["surgery_shock","respiratory","cardio","gastro","endocrine","nephrology","urology","immune_rheum","skin_burns","senses","neuro","musculoskeletal","onco_hematology"];
const CAT_LABELS = {};
TOPICS.forEach(t => { CAT_LABELS[t.cat] = t.catLabel; });
